# Generated by Django 4.2.5 on 2023-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='gallery',
            field=models.ManyToManyField(to='work_samples.worksampleimage'),
        ),
    ]
