# Generated by Django 4.2.5 on 2023-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0002_worksample_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSampleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='worksample',
            name='tags',
            field=models.ManyToManyField(to='work_samples.worksampletag'),
        ),
    ]
